import os

import pytest

import ocr_input


def test_parse_xml():
    sample_path = "test/ocr"
    file_l = os.listdir(sample_path)

    content_l = [
        [
            "----------y-=~~ l 4 ",
            "C!~S1!IYh~._lhL~cLe Ir:QU~v v C_ c44e'll~ -_Co~'~~r~ ev~E' r\" vaMes _, _VaI, () e ^ C a 5 +e _ S a~~  ",
            "f1a~ ~. E~e L - G `*' t$? 7 -- a.i_h. ~ ~.,%tIb.. .. (~ --_±_:z__4 M~%k -_ s-gT P M .:~S&=lr~=S~~ ~S:nvr   -C~ -~ ",
            "n--,:~- n ~ . .. .....~'..  ",
        ],
        [
            "BROWN A I'47LCIAMSON=TO»ACCO CoRPt7RATIOAr_ __ 401 S.41~H AVENUE.~SUIT'E200 P.O. BOX 35(IS() - I~.OI?ISVILLE, KY 40232-5(19) . 00o108a 01 AB \x95'AUTO ` r3-n 6064 10168 _ COUNCIL FOR TOBACCO RESEARCH 122 E 42ND ST . . SUITE 2518 NEW YORK NY 10168-2599 L,IIII II II LJ I IJ,I,IJ J L I L IL I II VENDOR REP4ITTANCEADVICE VOUCHER DATE TNV INVOICE NUMBER RECEIVED DATE \"FUNDED BY BROWN & WILLIAMSON CIGARETTE SALES\" \t\t\tINVOICE NUMBER ~\tGROSS AMOUNT ~\tDISCOUNT AMOUNT\t..~ NET - - AMOUNT\t~ ~ REMITTANCE ~ DESCR IPTION TW2752]5\t0</26!01\t02/26/01\tDEC2000-JAN2001\t~ 349,114.OD\t. .00\t- 349.114.00\t_ ~\t\t.\t- ~\t. ..\t. . . ~\t.\t. . PAl'MENT DATE .._ ~a_rozioi   CHECK NUfdBER~ ~ ~\t VENDOR NUMBER\t ~~ TOTAL ~ ~ ~~At0UN7- I aouoesos9s j\t2oo04\t- -- ~aas,ii<,oo~ 70118067 "
        ],
        [
            "[38] Montreal, Canada: MUCTC Wants Its Cops To Get New Butt-Out Powers [39] United Kingdom; Kickers Can Win Pounds 2,000 Holiday [40] Christchurh, New Zealand: Govt Aids Smokers To Quit with $6m Package [41] Indianapolis, Indiana: The African Americans Targeted By Smoking Ad [42] Hyderabad, India: Commodities - Tobacco Alternatives Suggested In AP [43] Ireland, United Kingdom: New Anti-Smoking Drug Will Help More To Quit [44] California: Groups Line Up For Tax Revenue [45] Agawam, Massachusetts: Some Applaud Smoke Ban Change [46] Canada: Region Gets First Smoke Law Convictions [47] News South Wales, Australia: NSW Health Expert Urges Qld To Adopt Tobacco Licence [48] Ukraine: Tobacco Factories Output Rose By 22 Percent In June [49] Malaysia: Lighted Cigarette Butt 'No. 1 Foe' [50] Panama: Importer's Claims On Health Warning Denied [51] Hong Kong: Smuggled Cigarettes Discovered On Ship From China [52] Russia: Boutique Selling Danneman's New Product [53] Russia: Cigarette Production (54) Russia: Illegal Exports Suspected [55] Malaysia: Lit Cigarettes Main Cause Of Fire [56] Cuba: Bellotex To Make Tobacco Paper I RJR0000001129014217 700501040 ",
            "From: Simpson, Janis H. To: David Powers; Donald Foreman; Frank Lester; Jim Ellis; John Fish; John Singleton; Judy Albert; Karl Gallant; M, Hurst Marshall; Mike Phillips; Murray Jones; Randy Tompson; Roger Mozingo; Steve Strawsburg; Tommy Payne CC: BCC: Primary Date: 7/7/2000 2:08;10 PM Last Modified Date; 2000-Jul-07 14:08:11 Last Touched Date: Sent Date: 2(l(10-J ul-(17 14:08:10 Received Date: 2000-Jul-07 14:(18:10 Subject: TMA Topline ........ ..... .. .......... .......... ................................................_..,................... .----- ...----------- ...................... Attachments: '1'M A2(1O0-0707wo ] .doc RJR0000001129014217 700501038 ",
            "TMA News: 7-Jul-2000 WORLD [1] Montreal, Canada: Cigarette Makers Challenge Canada's Labeling Law [2) Buenos Aires, Argentina: Argentine Tobacco Companies Confident In Tax Deal [3) Washington, District of Columbia: Tobacco Money Flows Both Ways [4] Miami, Florida: Tobacco Attorneys Attack In Bid For Mistrial Ruling [5] Ottawa, Canada; Tobacco Firms Will Ask Court To Cancel Label Rules [6] Israel: Benizri To Seek Info On 'Radioactive Cigarettes' [7] Karachi, Pakistan: Tobacco Board Asks Trading Corporation Of Pakistan To Arrange Surplus Tobacco Export [8] New York: Philip Morris Takes Out $9 Billion Loan For Nabisco Purchase [9] Havana, Cuba: Cuban Cigar Leaf Shortfall Persists As Factories Remain Slow [10] Japan: Man Arrested For Allegedly Conspiring To Sell Fake Cigarettes [11] Washington, District of Columbia: Is Chelsea Clinton Lighting Up? [12] Maryland: Striking Out Tobacco At Ballparks [13] Olympia, Washington; State Kicks Off $15 Million Anti-Tobacco Program [14] South Carolina: South Carolina Tobacco Markets To Open In August As Production Quotas Decline [15] Miami, Florida: Florida Judge Denies Effort To Limit Punitives In Smokers' Trial [16] Miami, Florida: Tobacco Trial Jury Told Damage Award Can Top Firms' Net Worth [17) Little Rock, Arkansas: Wholesaler Appeals State Sanction For Tobacco Rebate Offer (18) United Kingdom: Smuggling Ministers 'Failing To Act' Over Alcohol And Tobacco Trade [19) Chongqing, China: Cigarette Ads Blamed For Increase In Young Smokers [20] New Zealand: Alcohol And Nicotine Withdrawal Blamed For Air Rage [21] Argentina: Export Increase Reported In Misiones, Argentina [22] Argentina: Low Leaf Prices Result In Lower Revenue [23] Argentina: Genetically Altered Tobacco? [24] Dominican Republic: Cigar Industry [25] Indonesia: High Clove Prices Reported [26] Montreal, Canada: Cigarette Label Law Under Fire [27] Hernando, Mississippi: Tobacco Company Chemist Testifies In Wrongful Death Lawsuit [28] California: Grand Terrace Activist Fights To Clear The Air: A 12-Year-Old Boy And Some Friends Gain Support From The City Council For Smoke-Free Parks [29] Canada: Shockerwick File [30] Miami, Florida: Judge KO's Tobacco Try On Damages [31] Little Rock, Arkansas: Huckabee Touts Ballot Issue, Submits Signatures (32] Miami, Florida: Judge To Decide On Tobacco Mistrial [33] Kampala, Uganda: BAT Promises Dividends [34] Corvallis, Oregon: Quit Line Helps Oregon State U. Students Quit Smoking [35] Raleigh, North Carolina: Senate Takes Fast Action On Big Bucks (36] Montreal, Canada: Tobacco Suit Far From Over: U.S. Ruling Offers Lots Of Room To Appeal [37] Salt Lake City, Utah: Senator Gets Anti-Tobacco Card RJR0000001 129014217 70050 1039 ",
        ],
        [
            "Cz~z,l G+~O ,t72)- Gd.c !tic d-u-G  C- srAKF - _ ~ / F~~ s7~'.Ci-, gr/r- ~ Ac4u,fi.z-tl 2~ ~~- s d ",
            " r \x95-- *~ ~yf~i~y ?~~ ~~9G  /Jd GK< . ~ (1E.~'GC~:f .rr.gorIe~) ,  CI~° ~ Gti~IrJ ",
            "~ ~-//-M~/ k~~ ,~~7-6 \x84 6~Gt%1o v t. ~.co ... G4~46a~s.,y//~ica4 al ~~ ~~ ~'\"°~`14 f ~ A\"`,~ ll7/ L-rO/ WP~aJah!/ Od 3 ~~ !~'~~ . ~ --_P __ i Z~~. ~~ ~ 44cew aw dalx~ ~~ ,P '1S --P- ~ktuX£ ~.ri~~ ... . ",
            "aye .. 91\", .G/,~y,//... S'alp // ~S  STd,c'F,/ ~I _-- ~ f- r~r ~_ Ar, ",
        ],
        [
            "a....~ .~.... -..x.o ........,\x95 . . . ., .. a~o.n.e...w« ~ ~ .. . SANdO PHACSINE WoRmS. Lmo. sosra osripm, 5.- Constant :Fee¢er for,~ Ni-B .. ; 1 set \" US$ 39, 560. - Capaci ' ` : 8 OOOK %tic \" . 9. ; \" ~elt Width1,000mn'x.45° - Nbtor \":' 2.95Kw x 2units.'' 1.9bon Ternis and oorrlitionsr' ; Time oE shipnent : Wft~ 12 ntmths after\"reoeipt- of your firm ordar ;` Terms,of paymer:t :\"3b8'by cash when byar-p ~' an order by cadsh wiahin 2 w~a4fter delivosry; , . ' This quotation: holds gopd until March 31, 1984 ",
            "a.~c. wonn... , -.wuio wnam+a-. . Messrs.:R. J. Reynolds,lsobacqo Ooqpany :. Winstart~Salem,'NC'27102~~ '  y N :.wx9\"4Sa .6,` '1983 _ <;; IF14F PROCESSING FACTORSlIS DQUIPMPSTi' '\t\t T, ('T',eI . s Fq; W~.nst~on-Salem, _ ., 1. -ViWesheis ,\t ~ 1.. New 7.SUiio TY:resher, mbd8l-Nf-8 l set \x95\tUS$199,670.- '\t e .~~ ~\t\tCapacity' c ,8.000Kg/HC (17,6001hs/Hr) '\t\t ~, i\t\tMotor :'A9.5Kw. 10.3ton r~ref n c:\t\t \t-2.:\t- ditto\"- model NP-4 l set\tUS$ 98,540:-\t \t\tCapacity.: 4,000Kq/FIf` (8,8001bs/Hr) ' Motor :'24.2Kw, 7:3toa\t\t -3.\t- ditto--- - model NT-2 1 set\tUS$ 54;820.-\"\t \tCapacity : 2,500Itq/H.r. (5,50011)i/Hr) Motor : 16.5K'w,.3.3ton\t\t .:: 2. Separator\t\t -1.. Cy\x95lindrical Separatpr Model CS-8\t1 set\t.US$ 84;290 '- , Capacity`: 8,000Kg%Hr Motor e `2:2Ktv, 3.7ton -2 --r ditt -- o 4 1\t\t  - , . , o M c :CS-4 e\t1 set\tUS$ 66,530. . CapaCity .: 4;000Kw, MotqY :\"1.5Kw,-2..6ton -3. ..-- ditto ----' Model CS-2\t  se\t  U3$ 57,920.- Capacity: i o 2.,50,0Kw ` MDtor :-1:5IQw, 1.9ton\t\t 3. Screen Separator for;cylindrical separator\t -1. Screen Separatc~~for CS-8\t1 set\tUSS 29,570.- Capacity . 575M[min . Motor : 1. 5Kw.' \x951.7tJon -2. - ditto - ',fpr CS-4\t  1 set\t  US$ 25.110.- Capacity i 350M3/:nin Motor :. 1.5Kw,'.O.,Bton -3. --- ditto --- for CS-2\t  1,set\t  US$ 21:420.-. Capacity : 260M3/min Motor : 1.5Kw, 0.7torr\t\t 4. Screen Separator between thresher and se(snrator\t -1. Screen Separator for NT-8 - CS-B 1\x95set\t;.US$ 26.040.~ Capacity: 400M3hnin ..\t Motor :,1.5Kw;~:U:94ton\t  dit ': - -\t~ \tto ---. for NT-4 CS 4 1 set\tUS$.19;500.-\tN \t Capacity . 200M3/mifl . Motor : 1.5Kw, 0:6t:an\t\tW N w  -3. - ditto w'\"'c.fpr Nf-2 - CS-2\" 1 set\t US$ 16,100.-\tLn ko \tCapacity 110M3/~ ` -  Motor : 0.75I(ta, 0:5ton\t\t\tm w .~.' . . ` . ._. _., ",
        ],
    ]

    for file, content in zip(file_l, content_l):
        assert ocr_input.parse_xml(os.path.join(sample_path, file)) == content, f"Error in file {os.path.join(sample_path, file)}"
